// prettier-ignore
export const actionMappings = {
  create: { base: 'create', past_tense: 'Created', label: 'Add', },
  edit: { base: 'edit', past_tense: 'Edited', label: 'Edit', },
  duplicate: { base: 'duplicate', past_tense: 'Duplicated', label: 'Clone', },
  delete: { base: 'delete', past_tense: 'Deleted', label: 'Remove', },
  archive: { base: 'archive', past_tense: 'Archived', label: 'Archive', },
  restore: { base: 'restore', past_tense: 'Restored', label: 'Restore', },
  approve: { base: 'approve', past_tense: 'Approved', label: 'Approve', },
  reject: { base: 'reject', past_tense: 'Rejected', label: 'Reject', },
  assign: { base: 'assign', past_tense: 'Assigned', label: 'Assign', },
  unassign: { base: 'unassign', past_tense: 'Unassigned', label: 'Unassign', },
  activate: { base: 'activate', past_tense: 'Activated', label: 'Activate', },
  deactivate: { base: 'deactivate', past_tense: 'Deactivated', label: 'Deactivate', },
  share: { base: 'share', past_tense: 'Shared', label: 'Share', },
  unshare: { base: 'unshare', past_tense: 'Unshared', label: 'Unshare', },
  complete: { base: 'complete', past_tense: 'Completed', label: 'Complete', },
  cancel: { base: 'cancel', past_tense: 'Canceled', label: 'Cancel', },
  download: { base: 'download', past_tense: 'Downloaded', label: 'Download', },
  upload: { base: 'upload', past_tense: 'Uploaded', label: 'Upload', },
  view: { base: 'view', past_tense: 'Viewed', label: 'View', },
  preview: { base: 'preview', past_tense: 'Previewed', label: 'Preview', },
  lock: { base: 'lock', past_tense: 'Locked', label: 'Lock', },
  unlock: { base: 'unlock', past_tense: 'Unlocked', label: 'Unlock', },
  notify: { base: 'notify', past_tense: 'Notified', label: 'Notify', },
  escalate: { base: 'escalate', past_tense: 'Escalated', label: 'Escalate', },
  decline: { base: 'decline', past_tense: 'Declined', label: 'Decline', },
  followUp: { base: 'followUp', past_tense: 'Followed Up', label: 'Follow Up', },
  update: { base: 'update', past_tense: 'Updated', label: 'Update', },
  import: { base: 'import', past_tense: 'Imported', label: 'Import', },
  export: { base: 'export', past_tense: 'Exported', label: 'Export', },
  test: { base: 'test', past_tense: 'Tested', label: 'Test', },
  validate: { base: 'validate', past_tense: 'Validated', label: 'Validate', },
  reorder: { base: 'reorder', past_tense: 'Reordered', label: 'Reorder Items', },
  synchronize: { base: 'synchronize', past_tense: 'Synchronized', label: 'Synchronize Items', },
  reset: { base: 'reset', past_tense: 'Reset', label: 'Reset', },
  setPriority: { base: 'setPriority', past_tense: 'Priority Set', label: 'Set Priority', },
  markAsRead: { base: 'markAsRead', past_tense: 'Marked as Read', label: 'Mark as Read', },
  markAsUnread: { base: 'markAsUnread', past_tense: 'Marked as Unread', label: 'Mark as Unread', },
  pin: { base: 'pin', past_tense: 'Pinned', label: 'Pin', },
  unpin: { base: 'unpin', past_tense: 'Unpinned', label: 'Unpin', },
  merge: { base: 'merge', past_tense: 'Merged', label: 'Merge', },
  split: { base: 'split', past_tense: 'Split', label: 'Split', },
  disable: { base: 'disable', pastTense: 'Disabled', title: 'Disable Feature', },
  submit: { base: 'submit', pastTense: 'Submitted', title: 'Submit Request', },
  confirm: { base: 'confirm', pastTense: 'Confirmed', title: 'Confirm Action', },
  deny: { base: 'deny', pastTense: 'Denied', title: 'Deny Request', },
  accept: { base: 'accept', pastTense: 'Accepted', title: 'Accept Offer', },
  start: { base: 'start', pastTense: 'Started', title: 'Start Task', },
  stop: { base: 'stop', pastTense: 'Stopped', title: 'Stop Task', },
  log: { base: 'log', pastTense: 'Logged', title: 'Log Action', },
  track: { base: 'track', pastTense: 'Tracked', title: 'Track Progress', },
  search: { base: 'search', pastTense: 'Searched', title: 'Search Item', },
  filter: { base: 'filter', pastTense: 'Filtered', title: 'Filter Results', },
  sort: { base: 'sort', pastTense: 'Sorted', title: 'Sort Items', },
  close: { base: 'close', pastTense: 'Closed', title: 'Close Window', },
  open: { base: 'open', pastTense: 'Opened', title: 'Open Window', },
  sync: { base: 'sync', pastTense: 'Synchronized', title: 'Sync Data', },
  remove: { base: 'remove', pastTense: 'Removed', title: 'Remove Item', },
  clean: { base: 'clean', pastTense: 'Cleaned', title: 'Clean Data', },
  configure: { base: 'configure', pastTense: 'Configured', title: 'Configure Settings', },
  calibrate: { base: 'calibrate', pastTense: 'Calibrated', title: 'Calibrate Device', },
  diagnose: { base: 'diagnose', pastTense: 'Diagnosed', title: 'Diagnose Issue', },
  resolve: { base: 'resolve', pastTense: 'Resolved', title: 'Resolve Issue', },
  clarify: { base: 'clarify', pastTense: 'Clarified', title: 'Clarify Issue', },
} as const
